server:
  port: 9999
  servlet:
    context-path: /dbExport
spring:
  application:
    name: db-export
  thymeleaf:
    cache: false
    charset: UTF-8
    prefix: classpath:/templates/thymeleaf/
    suffix: .html
    mode: HTML
    encoding: UTF-8
export:
  template-copy-path: .databaseExport